import type { Metadata } from "next";
import { Amaranth } from "next/font/google";
import "./globals.css";

export const amarnath = Amaranth({
  weight: ["400", "700"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={amarnath.className}>{children}</body>
    </html>
  );
}
